version: '2'

services:

### Application #############################
  application:
    image: tianon/true
    volumes:
      - ${APPLICATION}:/opt/htdoc

### Workspace #############################
  workspace:
    build:
      context: ./workspace
      args:
        - NODE_VERSION=${WORKSPACE_NODE_VERSION}
        - NODE_ENV=${NODE_ENV}
    volumes_from:
      - application
    depends_on:
      - application
    links:
      - platform:${PLATFORM_API_HOST}

### platform api #############################
  platform:
    build: ./platform
    volumes_from:
      - application
    volumes:
      - ${PLATFORM_NGINX_LOG_PATH}:/var/log/nginx
      - ${PLATFORM_NGINX_SITES_PATH}:/etc/nginx/sites-available
    ports:
      - "${PLATFORM_NGINX_HTTP_PORT}:80"
      - "${PLATFORM_NGINX_HTTPS_PORT}:443"
    depends_on:
      - application

### Web #############################
  web:
    build:
      context: ./web
      args:
        - NODE_ENV=${NODE_ENV}
    volumes_from:
      - application
    ports:
      - "${WEB_NODE_PORT}:8080"
    depends_on:
      - application
    links:
      - platform:${PLATFORM_API_HOST}

### mysql #############################
  mysql:
    build:
      context: ./mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${MYSQL_TIMEZONE}
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"

  mysql-slave:
    build:
      context: ./mysql-slave
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE_SLAVE}
      - MYSQL_USER=${MYSQL_USER_SLAVE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD_SLAVE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD_SLAVE}
      - TZ=${MYSQL_TIMEZONE}
    volumes:
      - ${MYSQL_DATA_PATH_SLAVE}:/var/lib/mysql
    ports:
      - "${MYSQL_PORT_SLAVE}:3306"
    links:
      - mysql:mysql-master