version: '2'

services:
  ### Application #############################
  application:
    image: tianon/true
    volumes:
      - ${MAVEN_LOCAL_REPOSITORY}:/root/.m2/repository
      - ${APPLICATION}/machinedog-gateway:/opt/htdoc/gateway
      - ${APPLICATION}/machinedog-discovery:/opt/htdoc/discovery
      - ${APPLICATION}/blog:/opt/htdoc/blog
      - ${APPLICATION}/water-article:/opt/htdoc/water-article
      - ${FRONT_LOG}:/var/log/front/nginx

### package #############################
  package:
    build:
      context: ./package
    volumes_from:
      - application

### Gateway #############################
  gateway:
    build:
      context: ${APPLICATION}/machinedog-gateway
    volumes_from:
      - application
    ports:
      - "8080:8080"
    extra_hosts:
      - "platform_v2:${PLATFORM_IP}"

### Discovery #############################
  discovery:
    build:
      context: ${APPLICATION}/machinedog-discovery
    volumes_from:
      - application
    ports:
      - "1111:1111"

### Security #############################
  security:
    build:
      context: ${APPLICATION}/machinedog-security
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    volumes_from:
      - application
    ports:
      - "5555:5555"

### Configserver #############################
  configserver:
    build:
      context: ${APPLICATION}/machinedog-configserver
    environment:
      - "SPRING_PROFILES_ACTIVE=prod,jdbc"
    volumes_from:
      - application
    extra_hosts:
      - "machinedog.yipzale.me:${MACHINEDOG_IP}"
    ports:
      - "9000:8080"

### Web #############################
  web:
    build:
      context: ${APPLICATION}/blog
      args:
        - NODE_ENV=${NODE_ENV}
    volumes_from:
      - application
    ports:
      - "${WEB_NODE_PORT}:8080"
    logging:
      driver: fluentd
      options:
        fluentd-address: "${FLUENTD_HOST}:24224"
        tag: "docker.web"


### platform api #############################
  platform_v2:
    build:
      context: ${APPLICATION}/water-article
    volumes_from:
      - application
    logging:
      driver: fluentd
      options:
        fluentd-address: "${FLUENTD_HOST}:24224"
        tag: "docker.platform"

### mysql #############################
  mysql:
    build:
      context: ./mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${MYSQL_TIMEZONE}
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    logging:
      driver: fluentd
      options:
        fluentd-address: "${FLUENTD_HOST}:24224"
        tag: "docker.mysql"

  mysql-slave:
    build:
      context: ./mysql-slave
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE_SLAVE}
      - MYSQL_USER=${MYSQL_USER_SLAVE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD_SLAVE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD_SLAVE}
      - TZ=${MYSQL_TIMEZONE}
    volumes:
      - ${MYSQL_DATA_PATH_SLAVE}:/var/lib/mysql
    ports:
      - "${MYSQL_PORT_SLAVE}:3306"
    links:
      - mysql:mysql-master
    logging:
      driver: fluentd
      options:
        fluentd-address: "${FLUENTD_HOST}:24224"
        tag: "docker.mysql-slave"

### Workspace #############################
  workspace:
    build:
      context: ./workspace
      args:
        - NODE_VERSION=${WORKSPACE_NODE_VERSION}
        - NODE_ENV=${NODE_ENV}
    volumes_from:
      - application

### fluentd #############################
  fluentd:
    build:
      context: ./fluentd
    volumes_from:
      - application
    volumes:
      - ${FLUENTD_DATA}:/fluentd/log
    ports:
       - "5140:5140"
       - "24224:24224"